from __future__ import annotations

from typing import Any

from core.orchestration.state import AgentState


class PRCreator:
    """Formats pull request bodies safely (no raw advisory body injection)."""

    @staticmethod
    def format_pr(state: AgentState) -> dict[str, str]:
        package_name = state.get("package_name") or "unknown"
        advisory_id = state.get("advisory_id") or "unknown"
        reasoning = state.get("reachability_reasoning") or "No detailed reasoning provided."
        current = state.get("current_version") or "?"
        fix = state.get("fixed_version") or "?"
        confidence = state.get("confidence")
        entrypoints = state.get("entrypoints") or []
        quotes = state.get("evidence_quotes") or []
        preflight = state.get("preflight_message")

        return PRCreator.format_from_scan(
            advisory_id=advisory_id,
            package_name=package_name,
            current=str(current),
            fix=str(fix),
            reasoning=reasoning,
            evidence_quotes=quotes if isinstance(quotes, list) else [],
            entrypoints=list(entrypoints),
            confidence=float(confidence) if confidence is not None else None,
            preflight_message=preflight if isinstance(preflight, str) else None,
        )

    @staticmethod
    def format_from_scan(
        *,
        advisory_id: str,
        package_name: str,
        current: str,
        fix: str,
        reasoning: str,
        evidence_quotes: list[dict[str, Any]],
        entrypoints: list[str],
        confidence: float | None,
        preflight_message: str | None,
    ) -> dict[str, str]:
        advisory_url = f"https://osv.dev/vulnerability/{advisory_id}"
        conf_str = f"{round(confidence * 100)}%" if confidence is not None else "n/a"
        ep_lines = "\n".join(f"- `{e}`" for e in entrypoints) or "- (none recorded)"

        quote_lines: list[str] = []
        for q in evidence_quotes[:5]:
            if not isinstance(q, dict):
                continue
            fp = q.get("file_path", "?")
            ls = q.get("line_start", "?")
            qt = str(q.get("quote", "")).replace("\n", " ").strip()
            quote_lines.append(f"- `{fp}:{ls}` — `{qt[:180]}`")
        if not quote_lines:
            quote_lines.append("- (no code quotes; see reasoning)")

        preflight_block = preflight_message or "not run"
        title = f"fix({package_name}): bump {current} → {fix} — remediate {advisory_id}"
        body = f"""## NotSudo Advisor — reachability-confirmed fix

**TL;DR:** Bump `{package_name}` `{current}` → `{fix}` for [{advisory_id}]({advisory_url}).

| Field | Value |
|------|--------|
| Verdict | `exposed` |
| Confidence | {conf_str} |
| Preflight | {preflight_block} |

### Why this is actually exposed
{reasoning}

### Reachable entry points
{ep_lines}

### Cited evidence (validated against source)
{chr(10).join(quote_lines)}

### Advisory
- [{advisory_id}]({advisory_url})
- Diff is a version bump only (no logic changes).

---
*Generated by NotSudo Advisor. Human review required — never auto-merged.*
"""
        return {"title": title, "body": body}
